# Generated by Django 5.0.4 on 2024-07-31 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FX_Profile', '0002_initial'),
        ('accounts', '0007_alter_official_cardy_cardy_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_Account', models.CharField(blank=True, choices=[('FB', 'FaceBook'), ('Tiktok', 'Tiktok')], max_length=50, null=True)),
                ('Social_slug', models.SlugField(default=uuid.uuid4)),
                ('Social_Link', models.URLField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SocialLinks', to='accounts.userbankaccount')),
            ],
        ),
    ]
