# Generated by Django 5.0.4 on 2024-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='Kra_Pin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='slug',
            field=models.SlugField(default='1c0d5d1ea46d5251c9f44b168e8c9fa9f66e6e9e165e329c7b98f198446d437b'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='slug_Confirm_You',
            field=models.SlugField(default=b'UD9rrmewUIeuzRrOv5+zU4O410xt14S/OAAp5JXvr7hUBn+pmMAgCTeqkyuoxOKaZsoru2jhpiza9ITWl9voZA==', null=True),
        ),
    ]
