# Generated by Django 5.0.4 on 2024-06-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraddress_kra_pin_alter_useraddress_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='Kra_Pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='slug',
            field=models.SlugField(default='f6b422b3971438c6411e725a8ba82b81ea593aa7552bc7128c53beacee64c25e'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='slug_Confirm_You',
            field=models.SlugField(default=b'9klHXF7q9D/8G05kVtN2PVybcgOKr8inM/sW+pJZUY/LDwYLGXD0/ZstK+nZCIbkG53aEDcMAMSdFH6Ogxn7qQ==', null=True),
        ),
    ]
