# Generated by Django 5.0.4 on 2024-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraddress_kra_pin_alter_useraddress_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='slug',
            field=models.SlugField(default='42c77b546bfc188f818c95105609bdb0e1369944dff24bb0189abfda62e73155'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='slug_Confirm_You',
            field=models.SlugField(default=b'vzFjVzFaX6yL43QcPIYD4ldnT+tP/CFJEmcVApcO6YJPwX56J31m1MofA/MOykSwlTh/OZBRfVWmOM07DICnjw==', null=True),
        ),
    ]
