# Generated by Django 5.0.4 on 2024-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraddress_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='slug',
            field=models.SlugField(default='17ef824a99d8ee9a62a9630daaa3e7f7704a6c40268c7bcc7aeb2ac6d907552e'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='slug_Confirm_You',
            field=models.SlugField(default=b'0jlHqdd4XFV4pYv04UTBthtGUAcSpYOiC+R2q/JmoPaN+fYZSYjvBKD1tfYHkzc05R6BBo040rcPa87d46rVhw==', null=True),
        ),
    ]
