# Generated by Django 5.0.4 on 2024-07-30 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraddress_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='slug',
            field=models.SlugField(default='5c10682c10721009a0ad41a7bae5ddbc4c003889b9a2a00cdf0320e6f80e42c7'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='slug_Confirm_You',
            field=models.SlugField(default=b'NbxndNYv3guAZSb90GXVp+ig3NLUmg7dRoQPWnuPhjyP6Kjj2l8SQ+TUPVVB38elvgyCcXueRQyLpUSW3HFyuQ==', null=True),
        ),
        migrations.CreateModel(
            name='Official_Cardy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardy_type', models.PositiveSmallIntegerField(choices=[('ID', 'National Identification Card'), ('Passport', 'Travel Passport'), ('NHIF', 'National Health Insurance Fund'), ('Drivers Licence', 'Driving Licence'), ('NSSF', 'NSSF Card'), ('Special Card', 'Persons With Disability Card')])),
                ('cardy_number', models.IntegerField(blank=True, null=True)),
                ('cardy_label', models.CharField(blank=True, max_length=50, null=True)),
                ('cardy_slug', models.SlugField(default=uuid.uuid4)),
                ('cardy_description', models.TextField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cardy_front_image', models.ImageField(default='img/Mboa Academy.jpg', upload_to='cardy_img')),
                ('cardy_Back_image', models.ImageField(default='img/Mboa Academy.jpg', upload_to='cardy_img')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardy', to='accounts.userbankaccount')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
