# Generated by Django 5.0.4 on 2024-07-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_useraddress_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official_cardy',
            name='cardy_type',
            field=models.CharField(blank=True, choices=[('National ID', 'National Identification Card'), ('Passport', 'Travel Passport'), ('NHIF Card', 'National Health Insurance Fund'), ('Drivers Licence', 'Driving Licence'), ('NSSF', 'NSSF Card'), ('Special Card', 'Persons With Disability Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='slug',
            field=models.SlugField(default='0b465daba56d0df9a07033b2d06c19f81395ae622f66196a4a14ac9f99040fbc'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='slug_Confirm_You',
            field=models.SlugField(default=b'xQSO9b5i0BruA2Bju0L3E9RtocoMe6W5sUmrkk7MTzjd9QxNzXTmziPLw9ObJz8ljaRGeFqnJ88o3riFvqut8g==', null=True),
        ),
    ]
