# Generated by Django 5.0.4 on 2024-06-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
