# Generated by Django 5.0.4 on 2024-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='post_id',
            field=models.SlugField(max_length=500),
        ),
    ]
