# Generated by Django 5.0.4 on 2024-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0004_alter_likepost_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
