# Generated by Django 5.0.4 on 2024-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Doo-In'), (5, 'MboaCoins'), (2, 'Doo-Out'), (3, 'Interest'), (4, 'Mboapay'), (6, 'Loan')]),
        ),
    ]
