# Generated by Django 5.0.4 on 2024-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openSoko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=b'i0jCRQ4CYwqMeKxyWwuSTK117PF94RGAQd2Ru1Vgs/CNfK6aOlH/yvGJSvKKtjCxmVa7Sc9vKe9iy/prVBByxg==', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code_confirm',
            field=models.CharField(blank=True, default='0661a6a0aebfa50f3b4be2c81097ba041016946590d9ab7f3a79a7b8ea7c31bd', max_length=200),
        ),
    ]
