# Generated by Django 5.0.4 on 2024-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openSoko', '0004_alter_order_ref_code_alter_order_ref_code_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=b'L9DibELsPrONPty2YLd7Q9ngLWn0+clVp40k6TnaZXAm58cAId04uhZt8QAxAp7XVtExFRizwR6jqyrLGjjGPg==', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code_confirm',
            field=models.CharField(blank=True, default='cb8bc9769fba7dd5bc785157108c5af48676480ff716450ed88797af1636f06e', max_length=200),
        ),
    ]
