# Generated by Django 5.0.4 on 2024-07-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openSoko', '0005_alter_order_ref_code_alter_order_ref_code_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=b'OtHLVARRKll+E9Zqd08bYL8IYYaz13UxN0lFS+L1m6FrXIRVQ9FigwN7/7EerB93pWfrYOr2JO1MFyU34/bYHA==', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code_confirm',
            field=models.CharField(blank=True, default='17e29026a786f9bb74ee81bd827f8a8d0e12b9028f6c2a4b7c53bc5057cd55c5', max_length=200),
        ),
    ]
