# Generated by Django 5.0.4 on 2024-07-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openSoko', '0006_alter_order_ref_code_alter_order_ref_code_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=b'6IPvcc3Me7ybhqKcP+NVGu6OpaAQ6y8+eU4hYsm/9FgQTIMMymjgAn8uDXYqbFZ2VUAr+Z0hUV8FWuNBEQBHvw==', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code_confirm',
            field=models.CharField(blank=True, default='ecdc766480805cf2dead88d22e07d3f230cb71c1a84488600bb2a768acee4967', max_length=200),
        ),
    ]
