# Generated by Django 5.0.4 on 2024-08-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openSoko', '0008_alter_order_ref_code_alter_order_ref_code_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=b'VI3HNSTkmepgxr25WYk3mGoYDdTGptkoJ+VH9Fpv3UKBqyLi8Ok9tL7DTQ4hym9MEyyIOJSv4RvtA6Ec+aJ8JQ==', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code_confirm',
            field=models.CharField(blank=True, default='bd2de74a5d329e2c9acce374429d0ffb9bb6e439e1606e475ea9b4afad117f21', max_length=200),
        ),
    ]
