# Generated by Django 5.1.3 on 2024-11-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openSoko', '0009_alter_order_ref_code_alter_order_ref_code_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=b'7n3p0Ei/j3kWHOr46W1lrqmeaL0DGcVqs4xVfAuUWyTgfFa57o5PsIVxLmbBvAGRb9tgtMCk3TgeUq1H1lJK7A==', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code_confirm',
            field=models.CharField(blank=True, default='58dabe0e679b4e9b711eac12ecfe9962c08c7fc4097e32329551ec4ce59c2b4a', max_length=200),
        ),
    ]
