# Generated by Django 5.1.3 on 2024-11-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openSoko', '0010_alter_order_ref_code_alter_order_ref_code_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=b'SlxK7lT+p4j3GLFAIGu0hgbbzkIKx5goQ8f4wqvnbDOFJsDvwqW3Ok6Weu33S1RBR019ShP+AUk0BlnvuItjVw==', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code_confirm',
            field=models.CharField(blank=True, default='6b4a31ab8d369005db0767ecb925594d5c09fa39b102eabbffeeab344d5996ab', max_length=200),
        ),
    ]
