# Generated by Django 5.1.3 on 2024-12-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openSoko", "0011_alter_order_ref_code_alter_order_ref_code_confirm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ref_code",
            field=models.CharField(
                blank=True,
                default=b"QEVCGSj0i0TC0wfwQYywp/YEYPrCgteZWrRa9FTgrBCyF9OJakVL4D/A67XeLKcT8qJ7UXyHD8Mn93ATmwr3TQ==",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="ref_code_confirm",
            field=models.CharField(
                blank=True,
                default="d501d72fcd6bbaa77619c9d26fdbe9fd2c4ffcc34b3fa68084b23e619df92b53",
                max_length=200,
            ),
        ),
    ]
