# Generated by Django 5.0.4 on 2024-06-05 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=256)),
                ('cortex_Name', models.CharField(default='Mboa Technologies', max_length=100)),
                ('cortex_Description', models.TextField(blank=True)),
                ('cortex_image', models.ImageField(default='blank-profile-picture.png', upload_to='Cortex')),
                ('cortex_Duration', models.CharField(max_length=30)),
                ('cortex_Price', models.IntegerField()),
                ('Programming_Language', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('C++', 'C++'), ('Kotlin', 'Kotlin'), ('Java', 'Java')], default='1', max_length=50)),
                ('posted_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=256)),
                ('Programming_Language', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('C++', 'C++'), ('Kotlin', 'Kotlin'), ('Java', 'Java')], default='1', max_length=50)),
                ('cortex_Name', models.CharField(default='Mboa Technologies', max_length=100)),
                ('content_Description', models.TextField(blank=True)),
                ('Book_Cover_image', models.ImageField(default='blank-profile-picture.png', upload_to='Cortex')),
                ('Published_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=120)),
                ('order', models.CharField(blank=True, max_length=200, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('outcome_type', models.CharField(blank=True, max_length=120, null=True)),
                ('seller_message', models.CharField(blank=True, max_length=120, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
