# Generated by Django 5.0.4 on 2024-06-05 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sleek_profile', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='Nerd',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraddress'),
        ),
        migrations.AddField(
            model_name='books',
            name='Nerd_Auther',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraddress'),
        ),
        migrations.AddField(
            model_name='charge',
            name='payment_profile',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraddress'),
        ),
    ]
